import sys
import os
import asyncio
from datetime import datetime

# Add parent backend directory to sys.path so imports resolve
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from database.mongodb import workouts_collection

CURATED_WORKOUT_TEMPLATES = [
    # --- TRACK & FIELD (10) ---
    {
        "id": "tpl-tf-1",
        "title": "100m Explosive Block Acceleration",
        "description": "High-intensity sprint start development targeting reaction time, first-step drive, and drive-phase transition.",
        "sport": "Track & Field",
        "category": "Speed",
        "difficulty": "Advanced",
        "duration_minutes": 45,
        "equipment": ["Starting Blocks", "Spikes", "Stopwatch"],
        "instructions": "1. 10m Dynamic Warm-up\n2. 5x Block Starts (10m drive)\n3. 3x 30m Acceleration Sprints with 3 min rest.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-tf-2",
        "title": "Flying 30m Sprint Max Velocity",
        "description": "Maximal velocity development focusing on upright posture, high knee lift, and minimal ground contact time.",
        "sport": "Track & Field",
        "category": "Speed",
        "difficulty": "Advanced",
        "duration_minutes": 40,
        "equipment": ["Timing Gates", "Spikes", "Cone Markers"],
        "instructions": "1. 20m acceleration build-up\n2. 30m maximum velocity fly zone\n3. Perform 4 repetitions with 4-5 minutes full recovery between reps.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-tf-3",
        "title": "Sprint Mechanics & A-Skip Drills",
        "description": "Fundamental sprint drill session to refine coordination, leg cycle mechanics, and front-side mechanics.",
        "sport": "Track & Field",
        "category": "Technique",
        "difficulty": "Beginner",
        "duration_minutes": 30,
        "equipment": ["Agility Ladder", "Mini Hurdles"],
        "instructions": "1. A-Walk 3x15m\n2. A-Skip 3x20m\n3. B-Skip 3x20m\n4. Fast-leg switches 4x10 reps per side.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-tf-4",
        "title": "Hill Sprint Power Session",
        "description": "Incline sprint training to develop posterior chain recruitment, aggressive drive angle, and ground force production.",
        "sport": "Track & Field",
        "category": "Strength",
        "difficulty": "Intermediate",
        "duration_minutes": 45,
        "equipment": ["Running Shoes", "Hill Incline"],
        "instructions": "1. 10-minute dynamic warm-up\n2. 6x 40m hill sprints at 95% effort\n3. Walk down slowly for full recovery after each rep.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-tf-5",
        "title": "Speed Endurance 5x200m",
        "description": "Lactic capacity workout tailored for 200m/400m sprinters building speed maintenance under heavy fatigue.",
        "sport": "Track & Field",
        "category": "Endurance",
        "difficulty": "Advanced",
        "duration_minutes": 50,
        "equipment": ["Track Spikes", "Stopwatch"],
        "instructions": "1. 15-minute warmup and strides\n2. 5x 200m sprints at 88-92% target race pace\n3. 4 minutes rest between runs.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-tf-6",
        "title": "Plyometric Power & Bound Circuit",
        "description": "Explosive lower-body plyometric training enhancing tendon stiffness, reactive rate of force development, and leap distance.",
        "sport": "Track & Field",
        "category": "Strength",
        "difficulty": "Intermediate",
        "duration_minutes": 40,
        "equipment": ["Plyo Boxes", "Soft Mat"],
        "instructions": "1. Depth Jumps 3x5 reps\n2. Alternate Bounding 4x30m\n3. Single-Leg Hurdle Hops 3x6 reps per leg.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-tf-7",
        "title": "Dynamic Sprint Warm-up Routine",
        "description": "Comprehensive pre-competition or pre-workout dynamic mobility sequence to prepare muscle tissue and nervous system.",
        "sport": "Track & Field",
        "category": "Mobility",
        "difficulty": "Beginner",
        "duration_minutes": 25,
        "equipment": ["Resistance Bands", "Foam Roller"],
        "instructions": "1. Light foam rolling 5 mins\n2. Leg swings (frontal/sagittal) 2x10 reps\n3. Walking lunge with twist 2x15m.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-tf-8",
        "title": "Sprint Mobility & Hip Flow",
        "description": "Targeted hip capsule, adductor, and hamstring mobility flow designed to unlock stride length and hip extension.",
        "sport": "Track & Field",
        "category": "Mobility",
        "difficulty": "Beginner",
        "duration_minutes": 30,
        "equipment": ["Stretching Strap", "Mat"],
        "instructions": "1. World's Greatest Stretch 5 reps/side\n2. 90/90 Hip Switches 2x10 reps\n3. Strap Hamstring Stretch 60s per leg.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-tf-9",
        "title": "Reaction Start Training",
        "description": "Auditory and visual cue reaction drills to sharpen block clearance speed and initial step frequency.",
        "sport": "Track & Field",
        "category": "Speed",
        "difficulty": "Intermediate",
        "duration_minutes": 35,
        "equipment": ["Reaction Balls", "Starting Blocks"],
        "instructions": "1. Partner ball drop catches 4x5 drops\n2. Gun/clap reaction starts 6x15m sprints.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-tf-10",
        "title": "Active Track Recovery Jog & Stretch",
        "description": "Low-intensity flush workout to accelerate lactate clearance and alleviate central nervous system fatigue post-race.",
        "sport": "Track & Field",
        "category": "Recovery",
        "difficulty": "Beginner",
        "duration_minutes": 30,
        "equipment": ["Yoga Mat", "Foam Roller"],
        "instructions": "1. 10 mins bare-foot grass jog\n2. Light dynamic stretches\n3. Static holding stretches for calves and hamstrings.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },

    # --- FOOTBALL (5) ---
    {
        "id": "tpl-fb-1",
        "title": "Ball Control & Dribbling Fundamentals",
        "description": "Tight-space footwork and ball mastery drills to enhance close control under pressure and rapid directional shifts.",
        "sport": "Football",
        "category": "Technique",
        "difficulty": "Beginner",
        "duration_minutes": 45,
        "equipment": ["Agility Cones", "Football", "Training Bibs"],
        "instructions": "1. Cone Slalom Dribbling 4x sets\n2. Inside-Out Sole Rolls 3x1 min\n3. 1v1 Change of Direction Grid 5 mins.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-fb-2",
        "title": "Agility Ladder & Acceleration Drills",
        "description": "High-speed multi-directional footwork session designed to improve deceleration mechanics and explosive lateral cuts.",
        "sport": "Football",
        "category": "Speed",
        "difficulty": "Intermediate",
        "duration_minutes": 40,
        "equipment": ["Agility Ladder", "Speed Cones", "Stopwatch"],
        "instructions": "1. Icky Shuffle 4x rounds\n2. 5-10-5 Shuttle Sprint 4x reps\n3. L-Drill Lateral Cut 3x per side.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-fb-3",
        "title": "Passing Accuracy & Wall Pass Circuit",
        "description": "Weight of pass, first-touch orientation, and give-and-go combination sequence for midfielders and attackers.",
        "sport": "Football",
        "category": "Technique",
        "difficulty": "Intermediate",
        "duration_minutes": 50,
        "equipment": ["Rebounder Wall", "Cones", "Footballs"],
        "instructions": "1. One-touch rebound wall passing 3x2 mins\n2. Open body position receiving 4x10 passes\n3. Long diagonal ping accuracy 5 reps per foot.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-fb-4",
        "title": "Sprint & Finishing Drill",
        "description": "High-intensity sprint effort combined with composure on goal under simulated defensive pressure.",
        "sport": "Football",
        "category": "Speed",
        "difficulty": "Advanced",
        "duration_minutes": 45,
        "equipment": ["Goal Posts", "Footballs", "Cones"],
        "instructions": "1. 15m Sprint round cone -> First time shot on goal (6 reps)\n2. Cross and volley finishing 5 reps per side.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-fb-5",
        "title": "Match Recovery & Foam Rolling Session",
        "description": "Post-match targeted muscle release targeting groin, quadriceps, and hamstrings to speed up muscular repair.",
        "sport": "Football",
        "category": "Recovery",
        "difficulty": "Beginner",
        "duration_minutes": 30,
        "equipment": ["Foam Roller", "Massage Ball", "Mat"],
        "instructions": "1. Foam roll quads/calves 2 mins per muscle\n2. Groin butterfly stretch 3x45s\n3. Lower back decompression stretch.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },

    # --- BASKETBALL (5) ---
    {
        "id": "tpl-bb-1",
        "title": "Defensive Footwork & Slide Circuit",
        "description": "Conditioning session focusing on low defensive stance retention, lateral shuffle speed, and closeout control.",
        "sport": "Basketball",
        "category": "Mobility",
        "difficulty": "Intermediate",
        "duration_minutes": 40,
        "equipment": ["Basketball Court", "Resistance Bands", "Cones"],
        "instructions": "1. Banded Lateral Defensive Slides 4x15 sec\n2. Zig-Zag Defensive Court Slides 3x full court\n3. Closeout & Contest Jump 5 reps per side.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-bb-2",
        "title": "Layup Finishing Series & Contact Drills",
        "description": "Drive and finish package developing body control, reverse layups, floater trajectories, and absorbing contact.",
        "sport": "Basketball",
        "category": "Technique",
        "difficulty": "Intermediate",
        "duration_minutes": 45,
        "equipment": ["Basketball", "Hoop", "Heavy Pad"],
        "instructions": "1. Mikan Drill 2 mins continuous\n2. Euro-Step Finishing 5 reps per side\n3. Contact Pad Drive Finishing 5 reps.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-bb-3",
        "title": "Shooting Mechanics & Spot-Up Shots",
        "description": "High-repetition shooting workout emphasizing set point consistency, elbow alignment, and foot dip on catches.",
        "sport": "Basketball",
        "category": "Technique",
        "difficulty": "Beginner",
        "duration_minutes": 50,
        "equipment": ["Basketball", "Hoop", "Rebounder Net"],
        "instructions": "1. Form shooting from 3 feet (20 makes)\n2. Mid-range 5-spot shooting (10 makes per spot)\n3. Free throws 4x5 reps between sets.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-bb-4",
        "title": "Vertical Jump & Elasticity Development",
        "description": "Lower-body power workout targeting vertical jump performance, landing absorption, and ankle stiffening.",
        "sport": "Basketball",
        "category": "Strength",
        "difficulty": "Advanced",
        "duration_minutes": 45,
        "equipment": ["Plyo Boxes", "Medicine Ball", "Jump Rope"],
        "instructions": "1. Jump Rope double-unders 3x45s\n2. Max Effort Box Jumps 4x4 reps\n3. Med Ball Overhead Slam Jumps 3x6 reps.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-bb-5",
        "title": "Full-Court Interval Conditioning",
        "description": "High-intensity court shuttle run session mimicking fast-break transitions and full-court press demands.",
        "sport": "Basketball",
        "category": "Endurance",
        "difficulty": "Advanced",
        "duration_minutes": 35,
        "equipment": ["Basketball Court", "Whistle", "Heart Rate Monitor"],
        "instructions": "1. 17s Full Court Suicide Shuttles 4x sets\n2. 1 min rest between sets\n3. Free throw shooting under fatigue after each set.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },

    # --- CRICKET (5) ---
    {
        "id": "tpl-cr-1",
        "title": "Batting Footwork & Crease Agility",
        "description": "Specific crease footwork drills training decisive front-foot drives, back-foot punches, and fast spin foot adjustment.",
        "sport": "Cricket",
        "category": "Technique",
        "difficulty": "Intermediate",
        "duration_minutes": 45,
        "equipment": ["Bat", "Cones", "Tennis Balls"],
        "instructions": "1. Front Foot Drive Shadow Swings 3x15 reps\n2. Drop Ball Back-Foot Punch 4x10 balls\n3. Cone Agility Crease Step-Outs 3x1 min.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-cr-2",
        "title": "Pace Bowling Warm-up & Shoulder Alignment",
        "description": "Shoulder joint mobilization, thoracic extension, and run-up acceleration builder for fast bowlers.",
        "sport": "Cricket",
        "category": "Mobility",
        "difficulty": "Beginner",
        "duration_minutes": 35,
        "equipment": ["Resistance Bands", "Leather Cricket Ball"],
        "instructions": "1. Banded Shoulder Dislocates 2x15 reps\n2. Bound Run-up Rhythm Steps 4x20m\n3. Target Spot Release Practice 3x6 balls.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-cr-3",
        "title": "Fielding Reflex & Slip Catching Drills",
        "description": "Reaction time and hand-eye coordination drills for close-in slip fielders and outfield diving catches.",
        "sport": "Cricket",
        "category": "Speed",
        "difficulty": "Intermediate",
        "duration_minutes": 40,
        "equipment": ["Katchet Board", "Reaction Balls", "Fielding Gloves"],
        "instructions": "1. Katchet deflection catches 4x12 catches\n2. Low-slip stance catches 3x15 reps\n3. High outfield catch and throw 5 reps.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-cr-4",
        "title": "Sprint Between Wickets & Shuttle Run",
        "description": "Cricket-specific 22-yard sprint repeat protocol with bat turn technique and sliding grounded turns.",
        "sport": "Cricket",
        "category": "Speed",
        "difficulty": "Advanced",
        "duration_minutes": 40,
        "equipment": ["Wickets", "Bat", "Timing Gates"],
        "instructions": "1. Single 22y Sprint with Bat 6x reps (30s rest)\n2. Double (2 Runs) Turn and Return 4x reps\n3. Triple (3 Runs) Max Effort 2x reps.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-cr-5",
        "title": "Rotator Cuff & Thoracic Mobility",
        "description": "Post-bowling and post-fielding restorative mobility routine focused on shoulder cuff stability and spine de-rotation.",
        "sport": "Cricket",
        "category": "Recovery",
        "difficulty": "Beginner",
        "duration_minutes": 30,
        "equipment": ["Foam Roller", "Light Dumbbells", "Mat"],
        "instructions": "1. Side-Lying Thoracic Windmills 2x8 per side\n2. Y-T-W Shoulder Raises 3x10 reps\n3. Foam roll upper back and lats.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },

    # --- GENERAL FITNESS (5) ---
    {
        "id": "tpl-gf-1",
        "title": "Full Body Compound Strength",
        "description": "Fundamental resistance routine built around squats, presses, and pulls for overall lean muscle development.",
        "sport": "General Fitness",
        "category": "Strength",
        "difficulty": "Intermediate",
        "duration_minutes": 60,
        "equipment": ["Barbell", "Dumbbells", "Bench"],
        "instructions": "1. Barbell Back Squat 4x8 reps\n2. Dumbbell Bench Press 3x10 reps\n3. Bent-Over Barbell Row 3x10 reps\n4. Plank 3x60s.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-gf-2",
        "title": "Core Stability & Anti-Rotation Flow",
        "description": "Targeted midsection training focusing on trunk bracing, rotational resistance, and lumbar protection.",
        "sport": "General Fitness",
        "category": "Strength",
        "difficulty": "Beginner",
        "duration_minutes": 35,
        "equipment": ["Cable Machine", "Ab Wheel", "Mat"],
        "instructions": "1. Pallof Press 3x12 per side\n2. Ab Wheel Rollouts 3x10 reps\n3. Deadbugs 3x12 reps per side.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-gf-3",
        "title": "Beginner High-Intensity Cardio HIIT",
        "description": "Fast-paced bodyweight and light equipment interval session designed to burn calories and boost aerobic threshold.",
        "sport": "General Fitness",
        "category": "Endurance",
        "difficulty": "Beginner",
        "duration_minutes": 30,
        "equipment": ["Kettlebell", "Jump Rope", "Timer"],
        "instructions": "1. Kettlebell Swings (40s work / 20s rest)\n2. Jump Rope (40s work / 20s rest)\n3. Mountain Climbers (40s work / 20s rest)\n4. Repeat 4 full rounds.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-gf-4",
        "title": "Full-Body Deep Tissue Mobility",
        "description": "Relaxing self-myofascial release and static stretch session to relieve postural tightness and joint stiffness.",
        "sport": "General Fitness",
        "category": "Mobility",
        "difficulty": "Beginner",
        "duration_minutes": 30,
        "equipment": ["Foam Roller", "Massage Ball", "Stretching Band"],
        "instructions": "1. Foam roll IT bands and calves 2 mins/leg\n2. Doorway Chest Stretch 2x45s\n3. Seated Hamstring Band Stretch 2x60s.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
    {
        "id": "tpl-gf-5",
        "title": "Functional Athletic Conditioning",
        "description": "High-power hybrid conditioning circuit combining metabolic conditioning tools for overall athleticism.",
        "sport": "General Fitness",
        "category": "Endurance",
        "difficulty": "Advanced",
        "duration_minutes": 50,
        "equipment": ["Medicine Ball", "Battle Ropes", "Rowing Machine"],
        "instructions": "1. 500m Row Sprint\n2. 20 Med Ball Slams\n3. 30s Battle Rope Waves\n4. Rest 90s, complete 5 total rounds.",
        "created_by": "system",
        "created_by_role": "admin",
        "is_public": True,
    },
]


async def seed_workouts() -> int:
    """
    Inserts workout templates into MongoDB only if they do not already exist.
    Matches by template 'id' or 'title'. Returns the count of newly inserted items.
    """
    inserted_count = 0
    now = datetime.utcnow()

    for tpl in CURATED_WORKOUT_TEMPLATES:
        template_doc = {**tpl}
        template_doc["created_at"] = now
        template_doc["updated_at"] = now

        # Use upsert with $setOnInsert to prevent duplicating existing templates
        res = await workouts_collection.update_one(
            {"$or": [{"id": tpl["id"]}, {"title": tpl["title"]}]},
            {"$setOnInsert": template_doc},
            upsert=True,
        )

        if res.upserted_id is not None:
            inserted_count += 1

    print(f"[seed_workout_library] Seeding completed. New items inserted: {inserted_count}/{len(CURATED_WORKOUT_TEMPLATES)}")
    return inserted_count


if __name__ == "__main__":
    asyncio.run(seed_workouts())
